Sprint 10
Stanny-Starczewski/imageFeed pull request #3
Opened 2023-03-04 19:16 UTC by Stanny-Starczewski

задача спринта 10 на ревью

2023-03-05 11:26 UTC, protos17 requested changes

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +            else { fatalError("Failed to prepare for: \(ShowWebViewSegueIdentifier)")
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +    private let ShowWebViewSegueIdentifier = "ShowWebView"
Константы принято называть с мальнькой буквы, рекомендую поправить

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    static let authorizeURLString = "https://unsplash.com/oauth/authorize"
Рекомендую вынести в Constants

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBOutlet weak var progressView: UIProgressView!
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Constants.swift
> +    let AccessKey = "EcpaR11Ji4Tz038kXvQV8KlBFEpB3mI5zdaBqkJ7gS0"
Константы принято называть с маленькой буквы, рекомендую поправить

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/Constants.swift
> +    let DefaultBaseURL = URL(string: "https://api.unsplash.com/")!
Рекомендую вынести их в класс Constants и обращаться через static let

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +        baseURL: URL(string: "https://unsplash.com")!
Рекомендую вынести в Constants

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +        return urlSession.data(for: request) {(result: Result<Data, Error>) in
Сильная ссылка, нужно добавить weak self, или decoder объявить при вызове case .success(let data)

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +                defaults.removeObject(forKey: "bearerToken")
Ключ рекомендую вынести в константу и обращаться к ней

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +    private let ShowAuthenticationScreenSegueIdentifier = "ShowAuthenticationScreen"
Константы принято называть с маленькой буквы, рекомендую поправить

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +        if let token = oauth2TokenStorage.token {
Константа token не используется, можно сравнить с nil, не вводя новую константу

2023-03-05 11:26 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            else {fatalError("Faild to prepare for \(ShowAuthenticationScreenSegueIdentifier)")}
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-05 16:01 UTC, Stanny-Starczewski commented on ImageFeed/Auth/AuthViewController.swift
> +            else { fatalError("Failed to prepare for: \(ShowWebViewSegueIdentifier)")
ок, сделано

2023-03-05 16:04 UTC, Stanny-Starczewski commented on ImageFeed/Auth/AuthViewController.swift
> +    private let ShowWebViewSegueIdentifier = "ShowWebView"
Так было приведено в учебнике - был ответ, что глобальные константы объявляются с заглавной. Это ж не глобальная? Поправил на строчную.

2023-03-05 16:15 UTC, Stanny-Starczewski commented on ImageFeed/Auth/WebViewViewController.swift
> +    static let authorizeURLString = "https://unsplash.com/oauth/authorize"
Ну ок, но Самостоятельная задача по учебнику (Спринт 10/15: 10 → Тема 2/8: Работа с Unsplash API → Урок 3/3) говорила только о определенном наборе, без указания добавления чего-то еще позднее, этот набор: 

...в проекте файл Constants.swift. В нём создайте константы AccessKey, SecretKey и RedirectURI. Сохраните в них Access key, Secret Key, Redirect URI вашего приложения.
Добавьте константу AccessScope — список доступов, разделённых плюсом.
Добавьте константу DefaultBaseURL и сохраните в неё базовый адрес API, который мы с вами видели в документации. Константа должна быть типа

2023-03-05 16:19 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    static let authorizeURLString = "https://unsplash.com/oauth/authorize"
Это просто рекомендации от меня, как улучшить код,это не противоречит учебнику

2023-03-05 16:39 UTC, Stanny-Starczewski commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBOutlet weak var progressView: UIProgressView!
Тоже жумал об этом, но в итоге решил ориентироваться на то, как приведено в учебнике. Поправил

2023-03-05 16:43 UTC, Stanny-Starczewski commented on ImageFeed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any) {
Тоже думал об этом, но в итоге решил ориентироваться на то, как приведено в учебнике. Поправил.

2023-03-05 16:49 UTC, Stanny-Starczewski commented on ImageFeed/Constants.swift
> +    let AccessKey = "EcpaR11Ji4Tz038kXvQV8KlBFEpB3mI5zdaBqkJ7gS0"
Вот тут я по ходу спринта менял и возвразал обратно, поскольку писали ответы почему так (глобальные константы) в комментариях к вопросам моих сокурсников. И заглавные было приведено в учебнике. Поправил на строчную.

2023-03-05 17:21 UTC, Stanny-Starczewski commented on ImageFeed/Constants.swift
> +    let DefaultBaseURL = URL(string: "https://api.unsplash.com/")!
Вынес, добавил static let, но использовал для класса уже имеюзееся название APIConstants

2023-03-05 17:24 UTC, Stanny-Starczewski commented on ImageFeed/SplashViewController/SplashViewController.swift
> +    private let ShowAuthenticationScreenSegueIdentifier = "ShowAuthenticationScreen"
поправил

2023-03-05 17:29 UTC, Stanny-Starczewski commented on ImageFeed/SplashViewController/SplashViewController.swift
> +            else {fatalError("Faild to prepare for \(ShowAuthenticationScreenSegueIdentifier)")}
поправил

2023-03-05 17:45 UTC, Stanny-Starczewski commented on ImageFeed/Auth/WebViewViewController.swift
> +    static let authorizeURLString = "https://unsplash.com/oauth/authorize"
ok

2023-03-05 18:03 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2Service.swift
> +        return urlSession.data(for: request) {(result: Result<Data, Error>) in
добавил decoder

2023-03-05 18:25 UTC, Stanny-Starczewski commented on ImageFeed/SplashViewController/SplashViewController.swift
> +        if let token = oauth2TokenStorage.token {
поправил

2023-03-05 21:03 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2Service.swift
> +        baseURL: URL(string: "https://unsplash.com")!
вынес

2023-03-05 21:18 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +                defaults.removeObject(forKey: "bearerToken")
и это сделал

2023-03-06 10:37 UTC, protos17 approved these changes

2023-03-06 10:37 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    private let decoder = JSONDecoder()
deocder не используется, потому что ты создаешь его локально, можно удалить

2023-03-06 10:37 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                    let object = try decoder.decode(OAuthTokenResponseBody.self, from: data)
Можно decoder вообще отдельно не создавать, а сразу обращаться к нему напрямую, если он вызывается только в одном месте: JSONDecoder().decode ...

2023-03-06 10:37 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                complition(result)
Небольшая опечатка, пишется completion

2023-03-06 10:37 UTC, protos17 commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +    init() {}
Лишний init лучше убрать, а если используется синглтон, то его нужно сделать private init() {}

2023-03-06 10:37 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +        guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration")}
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-06 21:01 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2Service.swift
> +    private let decoder = JSONDecoder()
спасибо, что напомнили: когда писал тоже обратил внимание, хотел удалить, но замотался с UI...

2023-03-06 21:06 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                    let object = try decoder.decode(OAuthTokenResponseBody.self, from: data)
логично, поправил

2023-03-06 21:09 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                complition(result)
спасибо, поправил

2023-03-06 21:12 UTC, Stanny-Starczewski commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +    init() {}
убрал

2023-03-06 21:15 UTC, Stanny-Starczewski commented on ImageFeed/SplashViewController/SplashViewController.swift
> +        guard let window = UIApplication.shared.windows.first else { fatalError("Invalid Configuration")}
тоже смотрел на это место, меняя в других fatalError, но замотался и не поменял, сейчас поправил

2023-03-06 22:18 UTC, merged