Sprint 13
Stanny-Starczewski/imageFeed pull request #6
Opened 2023-04-19 20:30 UTC by Stanny-Starczewski

2023-04-20 17:23 UTC, protos17 requested changes

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> -        }
Чтобы приложение не пыталось загрузить данные при UI тесте, рекомендую здесь добавить проверку, что обращаемся к видимым строкам:
        if let visibleIndexPaths = tableView.indexPathsForVisibleRows,
           visibleIndexPaths.contains(indexPath) {
...

2023-04-20 17:23 UTC, protos17 commented on Image FeedTests/ImageListPresenterSpy.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/Auth/WebViewPresenter.swift
> +public protocol WebViewPresenterProtocol {
Рекомендую убрать public здесь и по проекту, работаем в рамках одного проекта

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/Auth/WebViewPresenter.swift
> +    var authHelper: AuthHelperProtocol
Рекомендую указать как private let

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/Helpers/AuthConfiguration.swift
> +    init(accessKey: String, secretKey: String, redirectURI: String, accessScope: String, authURLString: String, defaultBaseURL: URL, code: String, authorizationPath: String, baseURL: URL) {
Для структур можно не писать инициализатор, они нам его предоставляют встроенным

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/Helpers/AuthHelper.swift
> +class AuthHelper: AuthHelperProtocol {
Рекомендую указать как final

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/Helpers/AuthHelper.swift
> +    let configuration: AuthConfiguration
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/ImageFeedUITests/ImageFeedUITests.swift
> +        loginTextField.typeText("spaceboyua@yahoo.com")
Не рекомедую добавлять в репозиторий логины и пароли, в том числе для тестов

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/ImageFeedUITests/ImageFeedUITests.swift
Этот файл лежит в файлах проекта, в самом проекте не отображается, рекомендую удалить его

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/ImageFeedUITests/ImageFeedUITests.swift
> +        passwordTextField.typeText("Barcelona2021")
Будь аккуратней с пушем паролей в открытые репозитории

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/ProfileView/ProfileViewController.swift
> +class ProfileViewController: UIViewController, ProfileViewControllerProtocol {
Рекомендую указать как final

2023-04-20 17:23 UTC, protos17 commented on ImageFeed/ProfileView/ProfileViewController.swift
> +    internal lazy var imageView : UIImageView = {
internal можно не писать, он идет по умолчанию, когда мы его не пишем. Рекомендую удалить здесь и везде в проекте, где используется

2023-04-20 17:23 UTC, protos17 commented on ImageFeed_UITests/ImageFeed_UITests.swift
> +        loginTextField.typeText("")
Рекомендую вынести в константы в начале класса, чтобы можно было заполнить и запускать тесты, просто пустыми не совсем ясно, куда и какие данные вводить

2023-04-21 05:11 UTC, Stanny-Starczewski reviewed
+ то, что не вошло в комментарии, ProgressHUD меня тоже давно смущал, еще с 11 спринта как появился, но так как замечаний не было к нему, не возращался к этой проблеме, ну а потом забыл про нее, замотавшись с более актуальными. Спасибо, поправил так: 

        ProgressHUD.colorBackground = .lightGray
        ProgressHUD.colorAnimation = .darkGray

2023-04-21 05:11 UTC, Stanny-Starczewski commented on Image FeedTests/ImageListPresenterSpy.swift
> +import Foundation
Забыл, спасибо что напомнили - поправил)

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/Auth/WebViewPresenter.swift
> +public protocol WebViewPresenterProtocol {
Хорошо, поправил везде

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/Auth/WebViewPresenter.swift
> +    var authHelper: AuthHelperProtocol
Указал

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/Helpers/AuthConfiguration.swift
> +    init(accessKey: String, secretKey: String, redirectURI: String, accessScope: String, authURLString: String, defaultBaseURL: URL, code: String, authorizationPath: String, baseURL: URL) {
Понял, поправил, спасибо!

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/Helpers/AuthHelper.swift
> +class AuthHelper: AuthHelperProtocol {
Указал

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/Helpers/AuthHelper.swift
> +    let configuration: AuthConfiguration
понял, спасибо, поправил

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ImageFeedUITests/ImageFeedUITests.swift
Вот тут вопрос, в Xcode не вижу его, ранее тоже обратил внимание, когда делал коммиты, что удаление его как-то не отразилось при отправке на GitHub, но скачав с GitHub свой проект и запустив увидел, что его нет, и ладно) У меня есть некоторый сумбурный опыт удаления файлов (который приводил к некоторым проблемам) - удалить у себя на локалке прямо из папки и одновременно на GitHub его? Еще нашел старый ImageFeedTests - который сейчас не используется, так как есть Image FeedTests, тоже удалять?

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ImageFeedUITests/ImageFeedUITests.swift
> +        loginTextField.typeText("spaceboyua@yahoo.com")
Это из версии файла который я удалил, как думал: спасибо что напомнили - указание было в учебнике, но так как UI тесты шли "так себе" в какой-то момент, на радостях что все же заработало, расслабился (или устал) и закоммител, увы, с логинами и паролями. Прошу прощения, больше не повторю этого.

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ImageFeedUITests/ImageFeedUITests.swift
> +        passwordTextField.typeText("Barcelona2021")
Это из версии файла который я удалил, как думал: спасибо что напомнили - указание было в учебнике, но так как UI тесты шли "так себе" в какой-то момент, на радостях что все же заработало, расслабился (или устал) и закоммител, увы, с логинами и паролями. Прошу прощения, больше не повторю этого.

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ImagesList/ImagesListViewController.swift
> -        }
Вот тут пока не совсем понял, все тесты UI у меня проходят успешно, а самой такой реализации уже нет - функция "отрефакторина" в ImageListPresenter, где нет tableView... Пока пытаюсь осознать и что делать UPD: Поправил там где есть tableView - в ImageListViewController

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ProfileView/ProfileViewController.swift
> +class ProfileViewController: UIViewController, ProfileViewControllerProtocol {
хорошо, указал

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ProfileView/ProfileViewController.swift
> +    internal lazy var imageView : UIImageView = {
Ох, мы обсуждали уже с наставником Денисом Сурковым, мне это добавил сам Xcode - и я уж не противился, Денис спросил, зачем? Я ответил, что Xcode добавил, и все - более от него небыло комментариев. Спасибо, что вы прояснили области видимости написав про @testable import ImageFeed - теперь лучше стало понятно!

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed_UITests/ImageFeed_UITests.swift
> +        loginTextField.typeText("")
Сделал, тоже думал об этом, кстати, но как небыло прямого указания - оставил на ревью как по учебнику)

2023-04-21 05:11 UTC, Stanny-Starczewski commented on ImageFeed/ImagesList/ImagesListViewController.swift
> -        }
И еще вопрос по: "UI тест testProfile не проверяет после нажатия на кнопку логаута, что открылся экран авторизации (пункт 6). В этом случае мы проверяем, что данная кнопка действительно позволяет выйти из профиля, а не то, что мы можем просто ее нажать" - так как тест у меня работает, и экран авторизации открылся - не совсем понял пока что тут делать (чекать что профиль обновился?), можно уточнить, пожалуйста? Заранее спасибо!) UPD Кажется понял - надо проверить по кнопке)

2023-04-22 06:03 UTC, protos17 approved these changes

2023-04-22 06:03 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +                print(error.localizedDescription)
Лишние принты по проекту рекомендую убрать, это уже будет законченный проект, а принты используем для дебага в процессе разработки

2023-04-22 06:03 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    lazy var presenter: ImagesListPresenterProtocol? = {
Рекомендую, если извне он не изменяется, а только читается, установить как private (set)

2023-04-22 06:03 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    var presenter: ImagesListPresenterProtocol? { get set }
Если он извне не устанавливается, рекомендую указать только get

2023-04-22 06:03 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> -        }
Молодец, что разобрался! Извини, не всегда я могу отвечать в комментариях, лучше в таких случаях обращаться к Наставнику

2023-04-22 06:03 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        guard let alert = presenter?.makeAlert(with: Error.self as! Error) else { return }
Сюда нужно передать ошибку из инициализатора (error) и рекомендация нигде не использовать принудительное извлечение опционала

2023-04-22 18:55 UTC, Stanny-Starczewski commented on ImageFeed/ImagesList/ImagesListPresenter.swift
> +                print(error.localizedDescription)
Поправлю, спасибо

2023-04-22 18:55 UTC, Stanny-Starczewski commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    lazy var presenter: ImagesListPresenterProtocol? = {
ок

2023-04-22 18:56 UTC, Stanny-Starczewski commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +    var presenter: ImagesListPresenterProtocol? { get set }
ок

2023-04-22 18:56 UTC, Stanny-Starczewski commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +        guard let alert = presenter?.makeAlert(with: Error.self as! Error) else { return }
понял

2023-04-24 21:14 UTC, merged